name: onestop_mobile_app
description: Mobile application for OneStop Application Services LLC.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0
  supabase_flutter: ^2.3.0
  url_launcher: ^6.2.2
  intl: ^0.19.0
  image_picker: ^1.2.1
  flutter_staggered_animations: ^1.1.1
  http: ^1.1.0
  flutter_stripe: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_image.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1A365D"
  adaptive_icon_foreground: "assets/logo_image.png"

flutter:
  uses-material-design: true

  assets:
    - assets/hero-image.png
    - assets/hero-image2.png
    - assets/img_dagi.jpg
    - assets/logo_image.png
    - assets/
